[project]
name = "bloomer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rein Van Imschoot", email = "reinvanimschoot@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "onnxruntime>=1.30.0",
    "onnxscript>=0.7.2",
    "scipy>=1.18.1",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[project.scripts]
bloomer-export = "bloomer.export:main"
bloomer-test = "bloomer.test:main"
bloomer-train = "bloomer.train:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
